modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (25 is current forge version)
[[mods]] #mandatory
modId="forbidden_arcanus" #mandatory
version="1.15.1-1.0-beta-1" #mandatory
 # A display name for the mod
displayName="Forbidden & Arcanus" #mandatory
credits="stal111, Xesar_Zk" #optional
authors="stal111, Xesar_Zk" #optional
# The description text for the mod (multi line!) (#mandatory)
description=''' '''